`timescale 1ns/1ps

module tb_async_fifo;

    // =========================================================================
    // PARAMETERS
    // =========================================================================

    parameter int DATA_WIDTH = 32;
    parameter int ADDR_WIDTH = 4;       // FIFO depth = 2^ADDR_WIDTH = 16

    realtime WCLK_PERIOD = 10.0;
    realtime RCLK_PERIOD = 25.0;


    // =========================================================================
    // DUT SIGNALS
    // =========================================================================

    logic                       iso_en;

    logic                       wclk;
    logic                       wrst_n;
    logic                       w_inc;
    logic [DATA_WIDTH-1:0]      w_data;
    logic                       w_full;

    logic                       rclk;
    logic                       rrst_n;
    logic                       r_inc;
    logic [DATA_WIDTH-1:0]      r_data;
    logic                       r_empty;


    // =========================================================================
    // SCOREBOARD
    // =========================================================================

    logic [DATA_WIDTH-1:0] ref_queue[$];

    // Expected data waiting for synchronous BRAM read result.
    logic [DATA_WIDTH-1:0] expected_pipe[$];

    int pass_count = 0;
    int fail_count = 0;

    // Number of transactions generated by concurrent tests.
    int concurrent_write_count = 0;
    int concurrent_read_count  = 0;


    // =========================================================================
    // DUT
    // =========================================================================

    async_fifo #(
        .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) u_dut (
        .iso_en  (iso_en),

        .wclk    (wclk),
        .wrst_n  (wrst_n),
        .w_inc   (w_inc),
        .w_full  (w_full),
        .w_data  (w_data),

        .rclk    (rclk),
        .rrst_n  (rrst_n),
        .r_inc   (r_inc),
        .r_empty (r_empty),
        .r_data  (r_data)
    );


    // =========================================================================
    // CLOCK GENERATORS
    // =========================================================================

    initial begin
        wclk = 1'b0;

        forever begin
            #(WCLK_PERIOD / 2.0);
            wclk = ~wclk;
        end
    end


    initial begin
        rclk = 1'b0;

        forever begin
            #(RCLK_PERIOD / 2.0);
            rclk = ~rclk;
        end
    end


    // =========================================================================
    // RESET TASK
    // =========================================================================

    task automatic apply_reset();

        begin

            $display("");
            $display("--------------------------------------------------");
            $display("[%0tns] Applying Asynchronous Reset...", $time);
            $display("--------------------------------------------------");

            wrst_n = 1'b0;
            rrst_n = 1'b0;

            w_inc  = 1'b0;
            r_inc  = 1'b0;

            w_data = '0;

            iso_en = 1'b0;

            // Reset scoreboard.
            ref_queue.delete();
            expected_pipe.delete();

            // Allow both clock domains to observe reset.
            #(WCLK_PERIOD * 8);

            wrst_n = 1'b1;
            rrst_n = 1'b1;

            $display(
                "[%0tns] Reset Released. Scoreboard reset.",
                $time
            );

            // Allow CDC synchronizers to settle.
            #(WCLK_PERIOD * 3);

        end

    endtask


    // =========================================================================
    // WRITE TASK
    //
    // Drives request before active write edge.
    //
    // IMPORTANT:
    // The scoreboard records the transaction based on the FIFO flag value
    // BEFORE the write edge.
    // =========================================================================

    task automatic write_one(
        input logic [DATA_WIDTH-1:0] data
    );

        logic accepted;

        begin

            @(negedge wclk);

            w_data = data;
            accepted = !w_full;
            w_inc = 1'b1;

            @(posedge wclk);

            if (accepted) begin

                ref_queue.push_back(data);

                $display(
                    "[%0tns] [WRITE] Pushed data: 0x%0h | Ref Queue Depth: %0d",
                    $time,
                    data,
                    ref_queue.size()
                );

            end
            else begin

                $display(
                    "[%0tns] [EDGE CHECK - OVERFLOW] Write rejected while FULL. Data: 0x%0h",
                    $time,
                    data
                );

            end

            @(negedge wclk);

            w_inc = 1'b0;

        end

    endtask


    // =========================================================================
    // READ TASK
    //
    // Issues a read request.
    //
    // IMPORTANT:
    // The expected data is added to expected_pipe when the READ REQUEST is
    // accepted. The checker below checks that value on the NEXT rclk because
    // the BRAM read is synchronous.
    // =========================================================================

    task automatic read_one();

        logic [DATA_WIDTH-1:0] expected_data;
        logic                  accepted;

        begin

            @(negedge rclk);

            accepted = !r_empty;

            if (accepted) begin

                if (ref_queue.size() > 0) begin

                    expected_data = ref_queue.pop_front();

                    // Expected result of this read will be checked
                    // on the following read clock.
                    expected_pipe.push_back(expected_data);

                    r_inc = 1'b1;

                end
                else begin

                    fail_count++;

                    $display(
                        "[%0tns] [FAIL] DUT NOT EMPTY but reference queue is EMPTY!",
                        $time
                    );

                    r_inc = 1'b1;

                end

            end
            else begin

                r_inc = 1'b0;

                $display(
                    "[%0tns] [READ] FIFO EMPTY - read skipped.",
                    $time
                );

            end

            @(posedge rclk);

            @(negedge rclk);

            r_inc = 1'b0;

        end

    endtask


    // =========================================================================
    // READ OUTPUT CHECKER
    //
    // Checks the result of the PREVIOUS accepted read.
    //
    // This is intentionally delayed by one read clock.
    // =========================================================================

    always @(posedge rclk) begin

        if (!rrst_n) begin

            expected_pipe.delete();

        end
        else begin

            #1ps;

            if (expected_pipe.size() > 0) begin

                logic [DATA_WIDTH-1:0] expected_val;

                expected_val = expected_pipe.pop_front();

                if (r_data === expected_val) begin

                    pass_count++;

                    $display(
                        "[%0tns] [PASS] Read matched! Expected: 0x%0h, Got: 0x%0h",
                        $time,
                        expected_val,
                        r_data
                    );

                end
                else begin

                    fail_count++;

                    $display(
                        "[%0tns] [FAIL] Data mismatch! Expected: 0x%0h, Got: 0x%0h",
                        $time,
                        expected_val,
                        r_data
                    );

                end

            end

        end

    end


    // =========================================================================
    // WAIT UNTIL FIFO EMPTY
    // =========================================================================

    task automatic wait_until_empty();

        int timeout_count;

        begin

            timeout_count = 0;

            while (!r_empty && timeout_count < 100) begin

                read_one();

                timeout_count++;

            end

            if (timeout_count >= 100) begin

                fail_count++;

                $display(
                    "[%0tns] [FAIL] Timeout waiting for FIFO EMPTY.",
                    $time
                );

            end
            else begin

                $display(
                    "[%0tns] [EDGE CHECK PASS] FIFO EMPTY asserted.",
                    $time
                );

            end

        end

    endtask


    // =========================================================================
    // WAIT UNTIL FIFO FULL
    // =========================================================================

    task automatic wait_until_full();

        int timeout_count;

        begin

            timeout_count = 0;

            while (!w_full && timeout_count < 100) begin

                @(posedge wclk);

                timeout_count++;

            end

            if (w_full) begin

                $display(
                    "[%0tns] [EDGE CHECK PASS] FIFO FULL asserted.",
                    $time
                );

            end
            else begin

                fail_count++;

                $display(
                    "[%0tns] [FAIL] Timeout waiting for FIFO FULL.",
                    $time
                );

            end

        end

    endtask


    // =========================================================================
    // CONCURRENT WRITER
    //
    // Used by simultaneous read/write tests.
    //
    // This process runs independently of the reader process.
    // =========================================================================

    task automatic concurrent_writer(
        input int NUM_WRITES,
        input int WRITE_PROBABILITY
    );

        logic [DATA_WIDTH-1:0] data;
        int accepted_count;

        begin

            accepted_count = 0;

            repeat (NUM_WRITES) begin

                @(negedge wclk);

                data = $random;

                if (!w_full &&
                    ($urandom_range(0,99) < WRITE_PROBABILITY)) begin

                    w_data = data;
                    w_inc  = 1'b1;

                end
                else begin

                    w_inc = 1'b0;

                end

                @(posedge wclk);

                // Scoreboard write acceptance.
                if (w_inc && !w_full) begin

                    ref_queue.push_back(w_data);

                    accepted_count++;
                    concurrent_write_count++;

                    $display(
                        "[%0tns] [CONCURRENT WRITE] Data: 0x%0h | Ref Depth: %0d",
                        $time,
                        w_data,
                        ref_queue.size()
                    );

                end

                @(negedge wclk);

                w_inc = 1'b0;

            end

            $display(
                "[%0tns] Concurrent writer finished. Accepted writes: %0d",
                $time,
                accepted_count
            );

        end

    endtask


    // =========================================================================
    // CONCURRENT READER
    //
    // Runs independently from concurrent_writer().
    // =========================================================================

    task automatic concurrent_reader(
        input int NUM_READS,
        input int READ_PROBABILITY
    );

        logic [DATA_WIDTH-1:0] expected_data;
        int accepted_count;

        begin

            accepted_count = 0;

            repeat (NUM_READS) begin

                @(negedge rclk);

                if (!r_empty &&
                    ($urandom_range(0,99) < READ_PROBABILITY)) begin

                    r_inc = 1'b1;

                end
                else begin

                    r_inc = 1'b0;

                end

                @(posedge rclk);

                // Record accepted read.
                //
                // The read output itself will be checked by the
                // normal read checker one clock later.
                if (r_inc && !r_empty) begin

                    if (ref_queue.size() > 0) begin

                        expected_data = ref_queue.pop_front();

                        expected_pipe.push_back(expected_data);

                        accepted_count++;
                        concurrent_read_count++;

                        $display(
                            "[%0tns] [CONCURRENT READ] Expected: 0x%0h | Ref Depth: %0d",
                            $time,
                            expected_data,
                            ref_queue.size()
                        );

                    end
                    else begin

                        fail_count++;

                        $display(
                            "[%0tns] [FAIL] Concurrent read accepted but reference queue EMPTY!"
                        );

                    end

                end

                @(negedge rclk);

                r_inc = 1'b0;

            end

            $display(
                "[%0tns] Concurrent reader finished. Accepted reads: %0d",
                $time,
                accepted_count
            );

        end

    endtask


    // =========================================================================
    // CONCURRENT TEST
    //
    // Both clocks run independently.
    //
    // Writer and reader are launched using fork...join.
    // Therefore read and write operations overlap in time.
    // =========================================================================

    task automatic run_concurrent_test(
        input int NUM_WRITES,
        input int NUM_READS,
        input int WRITE_PROBABILITY,
        input int READ_PROBABILITY
    );

        begin

            concurrent_write_count = 0;
            concurrent_read_count  = 0;

            fork

                concurrent_writer(
                    NUM_WRITES,
                    WRITE_PROBABILITY
                );

                concurrent_reader(
                    NUM_READS,
                    READ_PROBABILITY
                );

            join

        end

    endtask


    // =========================================================================
    // VCD
    // =========================================================================

    initial begin

        $dumpfile("async_fifo_cases_1.vcd");

        $dumpvars(0, tb_async_fifo);

    end


    // =========================================================================
    // MAIN TEST SEQUENCE
    // =========================================================================

    initial begin

        logic [DATA_WIDTH-1:0] test_data;

        // ---------------------------------------------------------------------
        // Initial values
        // ---------------------------------------------------------------------

        w_inc  = 1'b0;
        r_inc  = 1'b0;
        w_data = '0;
        iso_en = 1'b0;

        wrst_n = 1'b0;
        rrst_n = 1'b0;


        // =====================================================================
        // CASE 1
        // SAME FREQUENCY / SAME PHASE
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 1: SAME FREQUENCY / SAME PHASE");
        $display("==================================================");

        WCLK_PERIOD = 20.0;
        RCLK_PERIOD = 20.0;

        apply_reset();

        // ---------------------------------------------------------
        // Write 10 entries
        // ---------------------------------------------------------

        repeat (10) begin

            test_data = $random;

            write_one(test_data);

        end

        // Allow pointer synchronization.
        #(WCLK_PERIOD * 4);

        // ---------------------------------------------------------
        // Read 10 entries
        // ---------------------------------------------------------

        repeat (10) begin

            read_one();

        end

        // Allow final read output/checker.
        #(RCLK_PERIOD * 4);


        // =====================================================================
        // CASE 2
        // FAST WRITE / SLOW READ
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 2: FAST WRITE / SLOW READ");
        $display("==================================================");

        WCLK_PERIOD = 10.0;
        RCLK_PERIOD = 40.0;

        apply_reset();

        // ---------------------------------------------------------
        // Fill FIFO
        // ---------------------------------------------------------

        repeat (16) begin

            test_data = $random;

            write_one(test_data);

        end

        #(WCLK_PERIOD * 3);

        if (w_full) begin

            $display(
                "[%0tns] [EDGE CHECK PASS] w_full asserted after FIFO flood.",
                $time
            );

        end
        else begin

            fail_count++;

            $display(
                "[%0tns] [EDGE CHECK FAIL] w_full did not assert.",
                $time
            );

        end

        // Give read domain time to receive write pointer.
        #(RCLK_PERIOD * 4);

        // ---------------------------------------------------------
        // Drain FIFO
        // ---------------------------------------------------------

        repeat (16) begin

            if (!r_empty) begin

                read_one();

            end
            else begin

                @(posedge rclk);

            end

        end

        #(RCLK_PERIOD * 5);


        // =====================================================================
        // CASE 3
        // SLOW WRITE / FAST READ
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 3: SLOW WRITE / FAST READ");
        $display("==================================================");

        WCLK_PERIOD = 40.0;
        RCLK_PERIOD = 10.0;

        apply_reset();

        // ---------------------------------------------------------
        // Write slowly
        // ---------------------------------------------------------

        repeat (5) begin

            test_data = $random;

            write_one(test_data);

            #(WCLK_PERIOD * 2);

        end

        // Allow read pointer synchronization.
        #(RCLK_PERIOD * 4);

        // ---------------------------------------------------------
        // Read quickly
        // ---------------------------------------------------------

        repeat (5) begin

            if (!r_empty) begin

                read_one();

            end
            else begin

                @(posedge rclk);

            end

        end

        #(RCLK_PERIOD * 5);


        // =====================================================================
        // CASE 4
        // READER STUCK / OVERFLOW
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 4: READER STUCK / OVERFLOW");
        $display("==================================================");

        WCLK_PERIOD = 10.0;
        RCLK_PERIOD = 10.0;

        apply_reset();

        r_inc = 1'b0;

        // ---------------------------------------------------------
        // Fill FIFO
        // ---------------------------------------------------------

        repeat (16) begin

            test_data = $random;

            write_one(test_data);

        end

        #(WCLK_PERIOD * 3);

        if (w_full) begin

            $display(
                "[%0tns] [EDGE CHECK PASS] FIFO correctly became FULL.",
                $time
            );

        end
        else begin

            fail_count++;

            $display(
                "[%0tns] [EDGE CHECK FAIL] FIFO did NOT become FULL.",
                $time
            );

        end

        // ---------------------------------------------------------
        // Attempt overflow write
        // ---------------------------------------------------------

        test_data = $random;

        @(negedge wclk);

        w_data = test_data;
        w_inc  = 1'b1;

        @(posedge wclk);

        if (w_full) begin

            $display(
                "[%0tns] [EDGE CHECK PASS] Overflow write correctly rejected. Data: 0x%0h",
                $time,
                test_data
            );

        end
        else begin

            fail_count++;

            $display(
                "[%0tns] [EDGE CHECK FAIL] Overflow write was NOT blocked!",
                $time
            );

        end

        @(negedge wclk);

        w_inc = 1'b0;

        // ---------------------------------------------------------
        // Drain FIFO
        // ---------------------------------------------------------

        #(RCLK_PERIOD * 3);

        $display(
            "[%0tns] Starting FIFO drain...",
            $time
        );

        wait_until_empty();

        #(RCLK_PERIOD * 5);


        // =====================================================================
        // CASE 5
        // CONTINUOUS SIMULTANEOUS READ + WRITE
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 5: CONTINUOUS SIMULTANEOUS R/W");
        $display("==================================================");

        // Deliberately unrelated clock periods.
        WCLK_PERIOD = 11.0;
        RCLK_PERIOD = 17.0;

        apply_reset();

        // ---------------------------------------------------------
        // First put some data into FIFO.
        //
        // This prevents the reader from spending the entire test
        // waiting for the first synchronized write pointer.
        // ---------------------------------------------------------

        repeat (8) begin

            test_data = $random;

            write_one(test_data);

        end

        #(RCLK_PERIOD * 4);

        // ---------------------------------------------------------
        // NOW BOTH DOMAINS RUN AT THE SAME TIME.
        //
        // Writer:
        //   600 write attempts
        //
        // Reader:
        //   600 read attempts
        //
        // Their clocks are independent.
        // ---------------------------------------------------------

        run_concurrent_test(
            600,
            600,
            70,
            70
        );

        // Allow pending read results and CDC synchronization.
        #(RCLK_PERIOD * 10);

        // Drain whatever remains.
        wait_until_empty();

        #(RCLK_PERIOD * 5);

        $display(
            "[%0tns] Concurrent Case 5 complete.",
            $time
        );

        $display(
            "[%0tns] Concurrent writes accepted: %0d",
            $time,
            concurrent_write_count
        );

        $display(
            "[%0tns] Concurrent reads accepted : %0d",
            $time,
            concurrent_read_count
        );


        // =====================================================================
        // CASE 6
        // SIMULTANEOUS TRAFFIC NEAR FULL
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 6: SIMULTANEOUS TRAFFIC NEAR FULL");
        $display("==================================================");

        WCLK_PERIOD = 13.0;
        RCLK_PERIOD = 19.0;

        apply_reset();

        // ---------------------------------------------------------
        // Start almost full.
        // ---------------------------------------------------------

        repeat (14) begin

            test_data = $random;

            write_one(test_data);

        end

        #(RCLK_PERIOD * 4);

        // ---------------------------------------------------------
        // Both sides active.
        //
        // Writer is aggressive.
        // Reader is deliberately slower.
        //
        // This exercises:
        //
        //     near FULL
        //     FULL assertion
        //     read freeing space
        //     write resuming
        //     pointer synchronization
        // ---------------------------------------------------------

        run_concurrent_test(
            500,
            500,
            90,
            45
        );

        #(RCLK_PERIOD * 10);

        wait_until_empty();

        #(RCLK_PERIOD * 5);


        // =====================================================================
        // CASE 7
        // SIMULTANEOUS TRAFFIC NEAR EMPTY
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 7: SIMULTANEOUS TRAFFIC NEAR EMPTY");
        $display("==================================================");

        WCLK_PERIOD = 17.0;
        RCLK_PERIOD = 11.0;

        apply_reset();

        // ---------------------------------------------------------
        // Start with only a few entries.
        // ---------------------------------------------------------

        repeat (3) begin

            test_data = $random;

            write_one(test_data);

        end

        #(RCLK_PERIOD * 4);

        // ---------------------------------------------------------
        // Reader is aggressive.
        // Writer is slower.
        //
        // This exercises:
        //
        //     EMPTY assertion
        //     EMPTY release
        //     pointer synchronization
        //     reads and writes overlapping around EMPTY
        // ---------------------------------------------------------

        run_concurrent_test(
            500,
            500,
            45,
            90
        );

        #(RCLK_PERIOD * 10);

        wait_until_empty();

        #(RCLK_PERIOD * 5);


        // =====================================================================
        // CASE 8
        // WRITER STUCK / UNDERFLOW
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 8: WRITER STUCK / UNDERFLOW");
        $display("==================================================");

        WCLK_PERIOD = 10.0;
        RCLK_PERIOD = 23.0;

        apply_reset();

        // ---------------------------------------------------------
        // Write only 4 entries.
        // ---------------------------------------------------------

        repeat (4) begin

            test_data = $random;

            write_one(test_data);

        end

        #(RCLK_PERIOD * 5);

        // ---------------------------------------------------------
        // Try reading more than the FIFO contains.
        // ---------------------------------------------------------

        repeat (10) begin

            if (!r_empty) begin

                read_one();

            end
            else begin

                $display(
                    "[%0tns] [EDGE CHECK] Read blocked correctly because FIFO is EMPTY.",
                    $time
                );

                @(posedge rclk);

            end

        end

        #(RCLK_PERIOD * 5);


        // =====================================================================
        // CASE 9
        // WRAP-AROUND TEST
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 9: POINTER WRAP-AROUND");
        $display("==================================================");

        WCLK_PERIOD = 12.0;
        RCLK_PERIOD = 18.0;

        apply_reset();

        // ---------------------------------------------------------
        // Repeatedly write/read small groups.
        //
        // This forces the address pointers to wrap around the
        // physical RAM several times without filling the FIFO.
        // ---------------------------------------------------------

        repeat (6) begin

            repeat (5) begin

                test_data = $random;

                write_one(test_data);

            end

            #(RCLK_PERIOD * 4);

            repeat (5) begin

                if (!r_empty) begin

                    read_one();

                end
                else begin

                    @(posedge rclk);

                end

            end

            #(WCLK_PERIOD * 3);

        end

        #(RCLK_PERIOD * 5);

        wait_until_empty();

        #(RCLK_PERIOD * 5);


        // =====================================================================
        // CASE 10
        // LONG RANDOMIZED SIMULTANEOUS STRESS
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("       CASE 10: LONG RANDOMIZED STRESS");
        $display("==================================================");

        WCLK_PERIOD = 10.0;
        RCLK_PERIOD = 17.0;

        apply_reset();

        // ---------------------------------------------------------
        // Begin with a few entries.
        // ---------------------------------------------------------

        repeat (5) begin

            test_data = $random;

            write_one(test_data);

        end

        #(RCLK_PERIOD * 4);

        // ---------------------------------------------------------
        // Long independent concurrent traffic.
        // ---------------------------------------------------------

        run_concurrent_test(
            2000,
            2000,
            65,
            65
        );

        // Allow CDC + pending RAM output.
        #(RCLK_PERIOD * 15);

        // Drain remaining entries.
        wait_until_empty();

        #(RCLK_PERIOD * 10);


        // =====================================================================
        // FINAL CHECKS
        // =====================================================================

        $display("");
        $display("==================================================");
        $display("             FINAL VERIFICATION");
        $display("==================================================");

        if (w_full === 1'bx) begin

            fail_count++;

            $display(
                "[%0tns] [FAIL] w_full is X.",
                $time
            );

        end

        if (r_empty === 1'bx) begin

            fail_count++;

            $display(
                "[%0tns] [FAIL] r_empty is X.",
                $time
            );

        end

        if (ref_queue.size() != 0) begin

            $display(
                "[%0tns] [WARNING] Reference queue contains %0d entries.",
                $time,
                ref_queue.size()
            );

        end

        if (expected_pipe.size() != 0) begin

            $display(
                "[%0tns] [WARNING] Expected pipeline contains %0d entries.",
                $time,
                expected_pipe.size()
            );

        end


        // =====================================================================
        // FINAL SUMMARY
        // =====================================================================

        $display("");
        $display("");
        $display("==================================================");
        $display("             VERIFICATION TEST SUMMARY");
        $display("==================================================");

        $display(
            " Total Successful Data Matches : %0d",
            pass_count
        );

        $display(
            " Total Mismatches / Errors     : %0d",
            fail_count
        );

        $display(
            " Remaining Reference Entries   : %0d",
            ref_queue.size()
        );

        $display(
            " Pending Output Checks         : %0d",
            expected_pipe.size()
        );

        $display("--------------------------------------------------");

        if ((fail_count == 0) &&
            (pass_count > 0) &&
            (ref_queue.size() == 0) &&
            (expected_pipe.size() == 0)) begin

            $display("");
            $display(" RESULT: ALL TEST CASES PASSED SUCCESSFULLY!");
            $display("");

        end
        else begin

            $display("");
            $display(" RESULT: TEST SUITE ENCOUNTERED FAILURES.");
            $display("");

        end

        $display("==================================================");


        #(RCLK_PERIOD * 3);

        $finish;

    end

endmodule
