// Auto-generated by OpenLane
module async_fifo(
`ifdef USE_POWER_PINS
  inout vssd1,
  inout vccd1,
`endif
  input iso_en,
  input wclk,
  input wrst_n,
  input w_inc,
  output w_full,
  input[31:0] w_data,
  input rclk,
  input rrst_n,
  input r_inc,
  output r_empty,
  output[31:0] r_data
);
endmodule
